#spring config
spring:
  aop:
    auto: true
  http:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 1000MB
  datasource:
    name: ceats
    url: jdbc:mysql://localhost:3306/ceats
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    maxActive: 1000
    initialSize: 5
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
## MyBatis
#mybatis:
#  type-aliases-package: com.zjm.model
#  mapper-locations: classpath:/mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#PageHelper
pagehelper:
  offsetAsPageNum: true
  rowBoundsWithCount: true
  reasonable: true
server:
  port: 8080
#Myconfig
filePath: src/main/resources/static/img/s
pageNum: 5
commentPageNum: 8

